import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Providers } from '../redux/provider'
import { AuthProvider } from "@/context/authContext";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Providers>

          <AuthProvider>

            <div className="sticky w-full z-10 top-0">
              <Header />
            </div>

            <div className="component">{children}</div>

            <Footer/>

          </AuthProvider>

        </Providers>

      </body>
    </html>
  );
}
